version: "3.9"

services:
  dev-ui:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
        read_only: true
      - dist:/usr/src/app/dist
    environment: 
      - SERVER_BASE
    # Pack ui files with parcel watcher
    command: [ "dev-ui" ]

  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - dist:/usr/src/app/dist
    environment: 
      - SERVER_BASE
    ports: 
      - "${HOST_PORT}:8080"
    user: $USER
    # Start dev server with nodemon watcher
    command: [ "dev" ]
    expose: 
      - "${HOST_PORT}"

volumes:
  dist:
